### ISSUE TITLE
This is a test issue....

### ISSUE THREAD

**Issue by rigor789** [rigor789/gh-issue-form-test#7]
### 

- [X] I have searched the existing issues as well as StackOverflow and this has not been posted before
- [X] Yes, this is a bug report
- [X] I agree to follow this project's Code of Conduct

### Current Behavior

When I click <Button>, `tap` is emitted.

### Expected Behavior

`tap` to be emitted. (same as now lol)

### Environment

```yaml
nativescript: 8.1.4
platform: darwin (x64)
node: 17.0.1
npm: 8.1.0
git: 2.30.1 (Apple Git-130)

# android
java: 1.8.0_265
javac: 1.8.0_265
adb: 1.0.41

# ios
XCode: 13.0.0
cocoapods: 1.11.2
```

### Dependencies

```json
"dependencies": {
  "@nativescript/core": "~8.1.1",
  "@nativescript/theme": "~3.0.1",
  "nativescript-vue": "~2.9.0"
},
"devDependencies": {
  "@nativescript/ios": "8.1.0",
  "@nativescript/types": "~8.1.1",
  "@nativescript/webpack": "~5.0.0",
  "@types/node": "~14.6.2",
  "nativescript-vue-template-compiler": "~2.9.0",
  "typescript": "~4.3.5",
  "vue": "~2.6.12"
}
```
