### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by rigor789** [rigor789/gh-issue-form-test#9]
### Issue Description

This works, but not when I don't write the code. Make it work in all cases please.

### Environment

```yaml
OS: macOS 11.5.1
CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
Shell: /bin/zsh
node: 17.0.1
npm: 8.1.0
nativescript: 8.1.4

# android
java: 1.8.0_265
ndk: 22.1.7171670
apis: 28, 29, 30, 31
build_tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3
system_images:
  - android-30 | Google APIs Intel x86 Atom
  - android-31 | Google APIs Intel x86 Atom_64

# ios
xcode: 13.0/13A233
cocoapods: 1.11.2
python: 2.7.16
python3: 3.9.5
ruby: 2.7.2
platforms:
  - iOS 15.0
  - DriverKit 20.4
  - macOS 11.3
  - tvOS 15.0
  - watchOS 8.0
```

### Dependencies

```json
"dependencies": {
  "@types/envinfo": "^7.8.1",
  "envinfo": "^7.8.1"
},
"devDependencies": {}
```

### 

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)
